=== SK91no/recalbox-stufff/board/recalbox/fsoverlay/recalbox/share_init/system/.emulationstation/es_bios.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="biosList">
    <xs:complexType>
      <xs:sequence>
	<xs:element name="system" maxOccurs="unbounded" minOccurs="1">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element name="bios" maxOccurs="unbounded" minOccurs="1">
		<xs:complexType>
		  <xs:simpleContent>
		    <xs:extension base="xs:string">
		      <xs:attribute type="xs:string" name="path" use="required"/>
		      <xs:attribute type="xs:string" name="md5" use="required"/>
		      <xs:attribute type="xs:string" name="core" use="required"/>
		      <xs:attribute type="xs:boolean" name="mandatory" use="optional"/>
		      <xs:attribute type="xs:boolean" name="hashMatchMandatory" use="optional"/>
		      <xs:attribute type="xs:string" name="note" use="optional"/>
		    </xs:extension>
		  </xs:simpleContent>
		</xs:complexType>
	      </xs:element>
	    </xs:sequence>
	    <xs:attribute type="xs:string" name="fullname" use="required"/>
	    <xs:attribute type="xs:string" name="platform" use="required"/>
	  </xs:complexType>
	</xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SK91no/recalbox-stufff/board/recalbox/fsoverlay/recalbox/share_init/system/.emulationstation/es_bios.xml
<?xml version="1.0" encoding="UTF-8"?>
<biosList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="es_bios.xsd">
  <system fullname="Amiga 600 (ECS/OCS)" platform="amiga600">
    <bios path="amiga/bios/kick33180.A500"     md5="85ad74194e87c08904327de1a9443b7a" core="amiberry" />
    <bios path="amiga/bios/kick34005.A500"     md5="82a21c1890cae844b3df741f2762d48d" mandatory="false" core="amiberry,libretro/amiberry,libretro/uae,libretro/uae4arm,libretro/uae4all" />
    <bios path="amiga/bios/kick37175.A500"     md5="dc10d7bdd1b6f450773dfb558477c230" core="amiberry,libretro/uae" />
    <bios path="amiga/bios/kick40063.A600"     md5="e40a5dfb3d017ba8779faba30cbd1c8e" mandatory="false" core="amiberry,libretro/amiberry,libretro/uae,libretro/uae4arm" />
    <bios path="amiga/bios/kick02019.AROS.ext" md5="4fa7042d73d0f77bf5723cf8430989bf" mandatory="false" core="amiberry,libretro/uae,libretro/uae4arm" note="AROS Free bios" />
    <bios path="amiga/bios/kick02019.AROS"     md5="186d23cccd9fbd6336d0f988b39dce4d" mandatory="false" core="amiberry,libretro/uae,libretro/uae4arm" note="AROS Free bios" />
  </system>
  <system fullname="Amiga 1200 (AGA)" platform="amiga1200">
    <bios path="amiga/bios/kick39106.A1200" md5="b7cc148386aa631136f510cd29e42fc3" core="amiberry" />
    <bios path="amiga/bios/kick40068.A1200" md5="646773759326fbac3b2311fd8c8793ee" core="amiberry,libretro/amiberry,libretro/uae,libretro/uae4arm" />
    <bios path="amiga/bios/kick40068.A4000" md5="9bdedde6a4f33555b4a270c8ca53297d" core="amiberry,libretro/amiberry,libretro/uae" note="This bios is required only for A4000 emulation" />
  </system>
  <system fullname="Amiga CDTV" platform="amigacdtv">
    <bios path="amiga/bios/kick34005.CDTV" md5="89da1838a24460e4b93f4f0c5d92d48d,d98112f18792ee3714df16a6eb421b89,
                                                d1145ab3a0f89340f94c9e734762c198" hashMatchMandatory="true" core="amiberry,libretro/amiberry,libretro/uae,libretro/uae4arm" mandatory="true" note="This bios is required only for CDTV emulation" />
  </system>
  <system fullname="Amiga CD32" platform="amigacd32">
    <bios path="amiga/bios/kick40060.CD32"     md5="f2f241bf094168cfb9e7805dc2856433,5f8924d013dd57a89cf349f4cdedc6b1" hashMatchMandatory="false" core="amiberry,libretro/amiberry,libretro/uae,libretro/uae4arm" mandatory="true" note="Use the combined ROM 'KS + extended v3.1 rev 40.060' or separate ROMs 'KS v3.1 rev 40.060 + Extended ROM rev 40.060'" />
    <bios path="amiga/bios/kick40060.CD32.ext" md5="bb72565701b1b6faece07d68ea5da639" core="amiberry,libretro/amiberry,libretro/uae,libretro/uae4arm" mandatory="false" note="Extended ROM rev 40.060" />
  </system>
  <system fullname="Apple IIGS" platform="apple2gs">
    <bios path="apple2gs1.rom" md5="20a0334c447cb069a040ae5be1d938df" core="gsplus" />
    <bios path="apple2gs3.rom" md5="ba89edf2729a28a17cd9e0f7a0ac9a39" core="gsplus" />
  </system>
  <system fullname="Apple Macintosh" platform="macintosh">
    <bios path="macintosh/MacII.ROM" md5="66223be1497460f1e60885eeb35e03cc" core="libretro/minivmac" />
    <bios path="macintosh/MinivMacBootv2.dsk" md5="16ddb8838d48be26e471a2f2bb85a961,e66dc7952c8b9673868ad2faba3c0d20" hashMatchMandatory="false" core="libretro/minivmac" />
  </system>
  <system fullname="Atari 8Bits" platform="atari800">
    <bios path="atari800/ATARIBAS.ROM" md5="0bac0c6a50104045d902df4503a4c30b" core="libretro/atari800" />
    <bios path="atari800/ATARIOSA.ROM" md5="eb1f32f5d9f382db1bbfb8d7f9cb343a" core="libretro/atari800" />
    <bios path="atari800/ATARIOSB.ROM" md5="a3e8d617c95d08031fe1b20d541434b2" core="libretro/atari800" />
    <bios path="atari800/ATARIXL.ROM"  md5="06daac977823773a3eea3422fd26a703" core="libretro/atari800" />
  </system>
  <system fullname="Atari 5200" platform="atari5200">
    <bios path="atari5200/5200.rom" md5="281f20ea4320404ec820fb7ec0693b38" mandatory="false" core="libretro/a5200,libretro/atari800" />
  </system>
  <system fullname="Atari 7800" platform="atari7800">
    <bios path="atari7800/7800 BIOS (U).rom" md5="0763f1ffb006ddbe32e52d497ee848ae" mandatory="false" core="libretro/prosystem" note="RUN ONLY US GAMES! Display official Atari logo." />
    <bios path="atari7800/7800 BIOS (E).rom" md5="397bb566584be7b9764e7a68974c4263" mandatory="false" core="libretro/prosystem" note="RUN ONLY EUROPEAN GAMES! Display official Atari logo." />
  </system>
  <system fullname="Elektronika BK" platform="bk">
    <bios path="bk/B11M_BOS.ROM" md5="fe4627d1e3a1535874085050733263e7" core="libretro/bk" />
    <bios path="bk/B11M_EXT.ROM" md5="dc52f365d56fa1951f5d35b1101b9e3f" core="libretro/bk" />
    <bios path="bk/BAS11M_0.ROM" md5="946f6f23ded03c0e26187f0b3ca75993" core="libretro/bk" />
    <bios path="bk/BAS11M_1.ROM" md5="1e6637f32aa7d1de03510030cac40bcf" core="libretro/bk" />
    <bios path="bk/DISK_327.ROM" md5="5015228eeeb238e65da8edcd1b6dfac7" core="libretro/bk" />
    <bios path="bk/FOCAL10.ROM"  md5="5737f972e8638831ab71e9139abae052" core="libretro/bk" />
    <bios path="bk/MONIT10.ROM"  md5="95f8c41c6abf7640e35a6a03cecebd01" core="libretro/bk" />
  </system>
  <system fullname="Sammy Atomiswave" platform="atomiswave">
    <bios path="dc/awbios.zip" md5="a420c0e56135c2e7e87399c887d7ef4a,abb0a508c83e689fc5e9230c623dabd0,
                                    042a0adecf2d616ccfb915a5cd71fde5,27fb8181fd9a0df18c7f6f941e9d60ab,
                                    74f5e994ecff655f18f0f9f998c9b1d9" core="libretro/flycast" />
  </system>
  <system fullname="Sega Naomi" platform="naomi">
    <bios path="dc/naomi.zip"    md5="7300a99a4fc856d1a3c36b4485789897,40ae83a9552df0f340d5eeeadc5436ea,
                                      7ed453bda92b25156536ff055b8685b6,a48e7a735b9036be8f150018155370ad,
                                      e1dcb105789296b93bf58e37b7f38fc6,3c6b0fb04ab3eae5dc6a99f63507dbd4" core="libretro/flycast" />
    <bios path="dc/airlbios.zip" md5="06dd41b614a6d6d079ec1ee73e2bf87d,5b7de05fb2dea6fb0408149c9bada27c,
                                      987e08b1786a93653281ca8a5b21dc7f" mandatory="false" hashMatchMandatory="false" core="libretro/flycast" note="Required only for the game 'Airline Pilots'" />
    <bios path="dc/hod2bios.zip" md5="09b92ad1240fba7954985bdee59d1741,2c08c42cc8c6eb3a4e07bff07db5102f,
                                      9e1f4846028b18b5ef8a6bd8efd6c67d,fbdf7e1cef86d3ffd23754c0a303a4af,
                                      729A623576CB9D8F7FD7C4E44ECE3066" mandatory="false" hashMatchMandatory="false" core="libretro/flycast" note="Required only for the game 'The House of the Dead 2'" />
  </system>
  <system fullname="Sega Naomi GD-Rom" platform="naomigd">
    <bios path="dc/naomigd.zip" md5="288cde03a112e7726fa8093e05d46853,416b5914acb3d0b4a190a1d358c8710d,
                                     bd9f19b4be0692e92e272d0eb82402f7,be57d3744e71a3396fb8dc59830e880a" core="libretro/flycast" />
  </system>
  <system fullname="Commodore 64" platform="c64">
    <bios path="vice/JiffyDOS_C64.bin"             md5="be09394f0576cf81fa8bacf634daf9a2" mandatory="false" core="libretro/vice_x64,libretro/vice_x64sc,libretro/vice_x128" note="JiffyDOS support" />
    <bios path="vice/JiffyDOS_C128.bin"            md5="cbbd1bbcb5e4fd8046b6030ab71fc021" mandatory="false" core="libretro/vice_x64,libretro/vice_x64sc,libretro/vice_x128" note="JiffyDOS support" />
    <bios path="vice/JiffyDOS_1541-II.bin"         md5="1b1e985ea5325a1f46eb7fd9681707bf" mandatory="false" core="libretro/vice_x64,libretro/vice_x64sc,libretro/vice_x128" note="JiffyDOS support" />
    <bios path="vice/JiffyDOS_1571_repl310654.bin" md5="41c6cc528e9515ffd0ed9b180f8467c0" mandatory="false" core="libretro/vice_x64,libretro/vice_x64sc,libretro/vice_x128" note="JiffyDOS support" />
    <bios path="vice/JiffyDOS_1581.bin"            md5="20b6885c6dc2d42c38754a365b043d71" mandatory="false" core="libretro/vice_x64,libretro/vice_x64sc,libretro/vice_x128" note="JiffyDOS support" />
    <bios path="vice/SCPU64/scpu-dos-1.4.bin"      md5="cda2fcd2e1f0412029383e51dd472095" mandatory="false" core="libretro/xscpu64" note="1.4 SuperCPU dos from SuperCPU64" />
    <bios path="vice/SCPU64/scpu-dos-2.04.bin"     md5="b2869f8678b8b274227f35aad26ba509" mandatory="false" core="libretro/xscpu64" note="2.04 SuperCPU dos from SuperCPU128" />
  </system>
  <system fullname="Sega Dreamcast" platform="dreamcast">
    <bios path="dc/dc_boot.bin"  md5="e10c53c2f8b90bab96ead2d368858623,d552d8b577faa079e580659cd3517f86,
                                      d407fcf70b56acb84b8c77c93b0e5327" hashMatchMandatory="false" core="libretro/flycast,reicast" />
    <bios path="dc/dc_flash.bin" md5="d6e11a23f1fa01cddb5dfccf7e4cc8d7,93a9766f14159b403178ac77417c6b68,
                                      0a93f7940c455905bea6e392dfde92a4,23df18aa53c8b30784cd9a84e061d008,
                                      69c036adfca4ebea0b0c6fa4acfc8538,74e3f69c2bb92bc1fc5d9a53dcf6ffe2,
                                      2f818338f47701c606ade664a3e16a8a" hashMatchMandatory="false" core="libretro/flycast,reicast" />
  </system>
  <system fullname="NEC PC-8800 Series" platform="pc88">
    <bios path="quasi88/n88.rom"      md5="22be239bc0c4298bc0561252eed98633,f7cba6a308c2718dbe97e60e46ddd66a,4f984e04a99d56c4cfe36115415d6eb8" core="libretro/quasi88" note="BASIC rom" />
    <bios path="quasi88/n88_0.rom"    md5="e28fe3f520bea594350ea8fb00395370,c254685f00ca9c31b97203d6ef19f5e2,d675a2ca186c6efcd6277b835de4c7e5" core="libretro/quasi88" note="BASIC rom #1" />
    <bios path="quasi88/n88_1.rom"    md5="e844534dfe5744b381444dbe61ef1b66,a8e298da7ac947669bcb1ff25cee0a83" core="libretro/quasi88" note="BASIC rom #2" />
    <bios path="quasi88/n88_2.rom"    md5="6548fa45061274dee1ea8ae1e9e93910,9d03154fd9abfc28c4e6d4dc705e6e23" core="libretro/quasi88" note="BASIC rom #3" />
